LOBES = {'frontal': ['caudalanteriorcingulate',
                     'caudalmiddlefrontal',
                     'lateralorbitofrontal',
                     'medialorbitofrontal',
                     'paracentral',
                     'parsopercularis',
                     'parsorbitalis',
                     'parstriangularis',
                     'precentral',
                     'rostralanteriorcingulate',
                     'rostralmiddlefrontal',
                     'superiorfrontal',
                     'frontalpole',
                     ],
         'parietal': ['inferiorparietal',
                      'isthmuscingulate',
                      'postcentral',
                      'posteriorcingulate',
                      'precuneus',
                      'superiorparietal',
                      'supramarginal',
                      ],
         'temporal': ['bankssts',
                      'entorhinal',
                      'fusiform',
                      'inferiortemporal',
                      'middletemporal',
                      'parahippocampal',
                      'superiortemporal',
                      'transversetemporal',
                      'temporalpole',
                      ],
         'occipital': ['cuneus',
                       'lateraloccipital',
                       'lingual',
                       'pericalcarine',
                       ],
         'insula': ['insula',
                    ],
         }


LOBE_COLORS = {'frontal': 60,
               'parietal': 24,
               'occipital': 41,
               'temporal': 10,
               'insula': 32,
               'unknown': 32}
